# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "10.11.12.13"
  config.ssh.forward_agent = true
  config.vm.synced_folder "/projects", "/home/vagrant/projects", :nfs => true
  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "./ansible/hosts"
    ansible.playbook = "./ansible/vagrant.yml"
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.limit = 'all'
  end
end
